### ISSUE TITLE
Move metadata from Linkset(rubygems.org table) to gemspec

### ISSUE THREAD

**Issue by arthurnn** [rubygems/rubygems.org#1127]
There are a lot of other threads that discuss this, but I wanted to create one issue with all the ideas and drawbacks here, so the community can take a conjunction decision.
### Current state

We have a table called [linksets](https://github.com/rubygems/rubygems.org/blob/5d93e745e22e102d1d1471f45a8d912a27f7dbbd/app/models/linkset.rb), which belongs to a gem. That table holds a few metadata for that gem, things like the documentation url, source code url, etc (you can find those when going to /edit in a rubygem you own, ie https://rubygems.org/gems/blankblank/edit)
### Suggestion

There was a few issues/prs (i.e https://github.com/rubygems/rubygems.org/pull/724) that propose we leverage the metadata field from the gemspec to populate those fields.
IMO, we should not have two canonical source of data for that. So we need to choose if we wanna threat the gemspec's metadata as that canonical source or not.
#### If we decide to move the data source of those fields to the gemspec file
- 👍 We can remove the form to edit that data, which will decrease complexity of rubygems.org
- 👍 Most of the fields that we display on the gem page are populated from the gemspec, so it would be more consistent to have the metadata coming from there too.
- 👍 We can have different documentation url by versions.
- 👎 Every time a gem wants to update those links, they would need to release a new version of the gem.

Tasks:
- [x] Add the metadata hash to the gem version table #858
- [x] Back fill that metadata for old gems #895
- [x] Read links from metadata and fallback to linkset #724
- [x] Deprecate the /edit page, and tell people to use the gemspec metadata info instead

related #718 https://github.com/rubygems/rubygems.org/issues/718#issuecomment-56129135 #724 #728 and probably others that I forgot, please cc them in the comments.

review:
@drbrain Is this the way to go, to use the gemspec instead? from https://github.com/rubygems/rubygems/issues/1007#issuecomment-54890247 I can tell you are 👍 with this change, can you confirm tho?
@qrush @evanphx You both have more context around the linkset, I guess that was created because the gemspec metadata didnt exist at that time, but anything else I missed?

cc @jimmycuadra @fwolfst @mpapis @kbrock @indirect @olivierlacan @pragtob @bf4

**Comment by kbrock** [comment]
thanks @arthurnn - I think you summarized this well.

Addional note, updating the `homepage` link required an update to the gem. The change here would require an update to the gem to update the other links aswell.

**Comment by dwradcliffe** [comment]
Yes important to note that we currently have a mix of both but it's not consistent.

**Comment by qrush** [comment]
Regarding:

> Every time a gem wants to update those links, they would need to release a new version of the gem.

I don't think this is a huge -1 for going forward with this plan. We've long treated gems like they are immutable once pushed up to the server. This is a step towards treating the gem's URLs the same way. I think we might see a small increase in the amount of support requests but as long as we have solid documentation + a good blog post explaining why, I think that's an OK compromise.

> You both have more context around the linkset, I guess that was created because the gemspec metadata didnt exist at that time, but anything else I missed?

The `Linkset` model was one of the first models introduced to Gemcutter circa 2009 in 50bc59040ae3876269e3311ee8ba064cc1471ff4. I wanted a way to express a group of links around a gem to help build a "home page" that every gem could use. This was also one of the important stances for what Gemcutter was _not_ to do: more detailed/custom home pages, wikis, docs, mailing lists, code hosting, bug tracking. All of those concerns were to be external - and the Linkset was the gateway out to those.

Since the introduction of the gemspec metadata, I've been hoping we could remove this model and its form altogether. I think we'd be better suited by a new model that `belongs_to :version` and has similar properties.

**Comment by jimmycuadra** [comment]
I have no objections to this plan. Sounds like a nice improvement!

**Comment by kbrock** [comment]
@qrush If this data is extracted from the metadata, do you still want a model? (albeit a non AR model)

**Comment by dwradcliffe** [comment]
I'd love to move forward here, any blockers?

**Comment by kbrock** [comment]
@dwradcliffe Please let me know what I can do to help.

I'm sure we could make the interface to linkset better. But you can always improve code.

For me, this feature is more about moving the community to incorporate more urls into the gemspec. Which is an orchestration effort across many related documentation and library projects.

Hope our diligence here will pay off and the integration into other projects will be easier.

**Comment by kbrock** [comment]
ok, I'm happy with #1234 as an alternative to #724 - but please let me know if you would like an alternative approach.

**Comment by sonalkr132** [comment]
We have completed all tasks on above mentioned checklist. ui form will be removed in 2 weeks from now.

**Comment by sonalkr132** [comment]
Check [guides](https://guides.rubygems.org/specification-reference/#metadata).
