### ISSUE TITLE
HTTP -> HTTPS at rubygems.org

### ISSUE THREAD

**Issue by esparta** [rubygems/rubygems.org#2425]
Some links in rubygems.org are pointing to the non-secure version of the sites, most of them have an internal redirection to their secure version, but we shall avoid that jump. 

## Proposal
I've identified the areas where it can be fixed:
- [x] Views with static links in HTML anchors - #2428 
- [x] Rails helpers & their test -  #2433
- [x] config/locales - #2430 
- [x] uptime.rubygems.org - #2459 

If accepted I can sent multiple PRs, or a single one with all the 25 files patched.

**Comment by dwradcliffe** [comment]
👍🏻 Anything hardcoded to http should be changed to https. Thanks!

**Comment by esparta** [comment]
The only missing secure link is the one for uptime.rubygems.org, which is currently not configured correctly having a `SSL_ERROR_BAD_CERT_DOMAIN` warning. I've checked the [Pingdom documentation Public Status Pages with custom domains](https://help.pingdom.com/hc/en-us/articles/205386171-Public-Status-Page) and looks like there's no way to have it working correctly with HTS.

customdomains:

**Comment by sonalkr132** [comment]
uptime.rubygems.org has https now

**Comment by esparta** [comment]
Nice, I've sent a PR to complete the work :)

**Comment by esparta** [comment]
Looks like we are done with this issue.
Thanks @sonalkr132  & @dwradcliffe  !
