### ISSUE TITLE
Checklist for MFA requirement release

### ISSUE THREAD

**Issue by jenshenny** [rubygems/rubygems.org#3163]
This issue tracks what should be completed for MFA enforcement on Aug 15
[RFC Phase 3 ](https://github.com/rubygems/rfcs/pull/36/files#diff-3d5cc3acc06fe7e9150fdbfc43399c5ad42572c122187774bfc3a4857df524f1R69-R86)

Required but should be merged before release
- [x] Redirect users to configure MFA on UI https://github.com/rubygems/rubygems.org/pull/3153
- [x] Modify mailer to send to affected users https://github.com/rubygems/rubygems.org/pull/3171

Deployed day of
- [x] Block privileged actions on CLI https://github.com/rubygems/rubygems.org/pull/3155
- [x] Remove `mfa_required` cookie for the UI https://github.com/rubygems/rubygems.org/pull/3170
- [x] Blog post outlining these changes https://github.com/rubygems/rubygems.github.io/pull/121
- [x] Run rake task to send emails to affected users

Enhancements (not required for release)
- [ ] Replace MFA device to prevent users to disable MFA https://github.com/rubygems/rubygems.org/issues/3142

**Comment by jenshenny** [comment]
@bettymakes @jchestershopify @kevinlinxc and I tophatted these flows on staging. We couldn't modify data on staging so we were only able to test some cases. cases highlighted with an asterisk were tested only on local

<details>

### User with more than 180 mil downloads
#### MFA disabled user
- [x] login to find MFA setup
Confirmed the following routes redirected to MFA setup:
/settings/edit
/dashboard
/gems/:rubygem_id/owners
/profile/api_keys
/profile/api_keys/new
/notifier
/sessions/verify
- [x] error for gem push
- [x] error for gem yank
- [x] error for gem add owner
- [x] error for gem remove owner
- [x] error for gem signin

#### MFA UI only user
- [x] login to find banner and redirect to settings, cannot navigate to authenticated pages
Confirmed the following routes redirected to edit settings:
/dashboard
/gems/:rubygem_id/owners
/profile/api_keys
/profile/api_keys/new
/notifier
/sessions/verify
- [x] error for gem push*
- [x] error for gem yank*
- [x] error for gem add owner*
- [x] error for gem remove owner*
- [x] error for gem signin

#### MFA UI_and_gem_signin user
- [x] nothing in login
- [x] no error for gem push
- [x] no error for gem yank
- [x] no error for gem add owner
- [x] no error for gem remove owner
- [x] no error for gem signin

### User with 165-180 mil downloads
#### MFA disabled user
- [x] login to find MFA setup, can navigate away*
- [x] warning for gem push*
- [x] warning for gem yank*
- [x] warning for gem add owner*
- [x] warning for gem remove owner*

#### MFA UI only user
- [x] login to find edit settings with warnings, can navigate away*
- [x] warning for gem push*
- [x] warning for gem yank*
- [x] warning for gem add owner*
- [x] warning for gem remove owner*

### User with less than 165 mil downloads
#### MFA disabled user
- [x] nothing in login
- [x] no error or warnings for gem push
- [x] no error or warnings for gem yank
- [x] no error or warnings for gem add owner
- [x] no error or warnings for gem remove owner

#### MFA UI only user
- [x] nothing in login*
- [x] no error or warnings for gem push*
- [x] no error or warnings for gem yank*
- [x] no error or warnings for gem add owner*
- [x] no error or warnings for gem remove owner*

 *unable to test on staging, tested on local machine
</details>

**Comment by bettymakes** [comment]
✅ Everything is complete in the check list besides the enhancement feature, which was not required for the release. We should be good to close this 🙌
